server:
  port: 8082
spring:
  application:
    name: resource-server
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost/springboot_oauth2_jwt?autoreconnect=true'
    password: root
    username: root

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        
security:
  jwt:
    public-key: classpath:mypublickey.txt

